# Generated by Django 4.1.7 on 2023-02-21 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerInfo',
            fields=[
                ('farmer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('experince', models.IntegerField(default=0)),
                ('profile_photo', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(default='الخرطوم', max_length=15)),
                ('avalability_for_job', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financing', models.IntegerField()),
                ('description', models.TextField()),
                ('location', models.CharField(default='الخرطوم', max_length=15)),
                ('duration', models.IntegerField(default=6)),
                ('space', models.IntegerField()),
                ('description_the_land', models.TextField(max_length=500)),
                ('irrigation_typemodels', models.CharField(max_length=500)),
                ('avalability', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorInfo',
            fields=[
                ('investor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('experince', models.IntegerField(default=0)),
                ('profile_photo', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(default='الخرطوم', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.IntegerField()),
                ('duration', models.IntegerField(default=6)),
                ('description', models.TextField(max_length=500)),
                ('price_rent', models.IntegerField()),
                ('Location', models.CharField(default='الخرطوم', max_length=15)),
                ('irrigation_typemodels', models.CharField(max_length=15)),
                ('avalability', models.BooleanField(default=False)),
                ('land_oner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pic', models.CharField(blank=True, max_length=500, null=True)),
                ('contnet', models.TextField(max_length=1000)),
                ('avalability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=35)),
                ('account_type', models.CharField(max_length=10)),
                ('account_avalability', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrerdLandRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='معلق', max_length=15)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_hogool.land')),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='معلق', max_length=15)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to=settings.AUTH_USER_MODEL)),
                ('invesment_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_hogool.investmentoffers')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='معلق', max_length=15)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invesment_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_hogool.investmentoffers')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerCrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_hogool.crops')),
            ],
        ),
    ]
