# Generated by Django 4.1.7 on 2023-02-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_hogool', '0003_remove_investorinfo_experince'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerinfo',
            name='full_name',
            field=models.CharField(default=' ', max_length=35),
        ),
        migrations.AddField(
            model_name='investmentoffers',
            name='title',
            field=models.TextField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='investorinfo',
            name='full_name',
            field=models.CharField(default=' ', max_length=35),
        ),
        migrations.AddField(
            model_name='land',
            name='title',
            field=models.TextField(default=' ', max_length=30),
        ),
    ]
