# Generated by Django 4.1.7 on 2023-02-24 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_hogool', '0004_farmerinfo_full_name_investmentoffers_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orerdlandrent',
            name='land_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='onerLand', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orerdlandrent',
            name='user_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestrer', to=settings.AUTH_USER_MODEL),
        ),
    ]
