# Generated by Django 4.1.7 on 2023-02-24 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_hogool', '0005_orerdlandrent_land_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproject',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creater1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerproject',
            name='investor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investor1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmerproject',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer1', to=settings.AUTH_USER_MODEL),
        ),
    ]
