# Generated by Django 4.1.7 on 2023-02-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_hogool', '0006_farmerproject_creater_farmerproject_investor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmerProject',
        ),
    ]
